# Generated by Django 4.1.5 on 2023-02-05 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gum',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gums', to=settings.AUTH_USER_MODEL),
        ),
    ]
