# Generated by Django 4.1.5 on 2023-02-08 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gum', '0002_alter_gum_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingum',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachingum',
            name='gum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gum', to='gum.gum'),
        ),
    ]
