# Generated by Django 4.1.5 on 2023-02-03 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to=settings.AUTH_USER_MODEL)),
                ('gum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='gum.gum')),
                ('kind_of_sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='gum.kindofsport')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.athlete')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.group')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='group',
            field=models.ManyToManyField(through='log.Membership', to='log.group'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='gum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gum.gum'),
        ),
    ]
